name: mkdocs-master

on:
  push:
    branches: [ master ]

jobs:
  publish-master:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set dev version
        run: echo "DEV_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Ev 'Download|INFO|WARNING')" >> $GITHUB_ENV

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install deps
        run: pip3 install 'git+https://github.com/logicalclocks/feature-store-api@master#egg=hsfs[docs]&subdirectory=python'

      - name: setup git
        run: |
          git config --global user.name Mike
          git config --global user.email mike@docs.hopsworks.ai

      - name: mike deploy docs
        run: mike deploy ${{ env.DEV_VERSION }} dev -u --push


