#!/bin/bash


HOME=%%scratch_dir%% JAVA_HOME=%%java_home%% HADOOP_HOME=%%hadoop_home%% HADOOP_USER_NAME=%%hadoop_user_name%% \
MATERIAL_DIRECTORY=%%certs_dir%% SPARK_YARN_STAGING_DIR='hdfs:///Projects/%%project%%/Resources/.sparkStaging exec /usr/lib/rstudio-server/bin/rsession "$@"
