package io.hops.hopsworks.common.dao.user.security.audit;

public enum AccountsAuditActions {
  USERMANAGEMENT("USER MANAGEMENT"),
  PROFILEUPDATE("PROFILE UPDATE"),
  LOSTDEVICE("LOST DEVICE REPORT"),
  CHANGEDSTATUS("CHANGED STATUS"),
  REGISTRATION("REGISTRATION"),
  SECQUESTIONCHANGE("SECURITY QUESTION CHANGE"),
  UNREGISTRATION("UNREGISTRATION"),
  RECOVERY("RECOVERY"),
  QRCODE("QR CODE"),
  PASSWORDCHANGE("PASSWORD CHANGE"),
  SECQUESTION("SECURTY QUESTION RESET"),
  PROFILE("PROFILE UPDATE"),
  PASSWORD("PASSWORD CHANGE"),
  TWO_FACTOR("TWO FACTOR CHANGE"),
  ABORTED("ABORTED"),
  FAILED("FAILED"),
  SUCCESS("SUCCESS"),
  ALL("ALL");

  private final String value;

  AccountsAuditActions(String value) { this.value = value; }

  @Override
  public String toString() { return value; }
}
