package se.kth.bbc.jobs;

/**
 *
 * @author stig
 */
public enum JobControllerEvent {
  MAIN_UPLOAD_FAILURE, MAIN_UPLOAD_SUCCESS, EXTRA_FILE_FAILURE, EXTRA_FILE_SUCCESS, STDOUT_DOWNLOAD_FAILURE, STDERR_DOWNLOAD_FAILURE, FILE_DOWNLOAD_FAILURE
}
