# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

gem "rspec", "3.4.0"
gem 'airborne', '0.2.5'
gem 'safe_attributes'
gem 'activerecord', '4.2.6'
gem 'mysql2', '0.4.4'
gem 'net-ssh', '~> 2.1.0'
gem 'session', '3.2.0'
gem 'coderay', '1.1.1'
gem 'rspec_junit_formatter'
gem 'file-tail'

group :development do
  gem 'dotenv'
  gem 'byebug'
  gem 'net-ssh-shell'
end

# gem "factory_girl", "~> 4"
# gem 'activerecord', '4.2.6', platform: :ruby
# gem 'activerecord-jdbc-adapter', '~> 1.3', platform: :jruby
# gem 'mysql2', '0.4.4', platform: :ruby
# gem 'jdbc-mysql', '~> 5.1', platform: :jruby
