name: pre-commit tests

on:
  pull_request_review:
    types: [submitted]

jobs:
  hopsworks-unit-tests:
    name: Hopsworks Unit Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'

      - name: Run unit tests
        run: mvn --batch-mode test

  hopsworks-vulnerability-checker:
    name: Hopsworks Vulnerability Checker
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'

      - name: Run vulnerability checker
        run: mvn clean install -Powasp-dependency-check,spot-bugs -DskipTests
